# Generated by Django 4.0.4 on 2022-07-08 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_orderitemm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItemm',
        ),
    ]
